services:
  database:
    container_name: database
    image: postgres:15
    environment:
      POSTGRES_DB: calendar_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d calendar_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=${API_PORT}
    env_file: .env
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - PORT=${FRONTEND_PORT}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    env_file: .env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  development:
    container_name: development
    command: sleep infinity
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app

volumes:
  postgres_data:
